#!/bin/bash

#
# Copyright 2018 SAS Institute Inc.
#
# This work is licensed under a Creative Commons Attribution 4.0 International License.
# You may obtain a copy of the License at https://creativecommons.org/licenses/by/4.0/ 
#

set -x

if [[ ! -d /opt/sas/vendor ]]
then
   echo "No /opt/sas/vendor found"
   exit
fi

cd /opt/sas/vendor

#
# This script tries to "do the right thing" for vendor artefacts needed (for example) by SAS/Access Software
# See all-in-one/VENDOR.md for the folder structure you should use to gove the "right thing" the best chance of happening correctly
#

cd /opt/sas/vendor
printf "\n\n%s\n\n" "These are the files we found in /opt/sas/vendor"
ls -alR /opt/sas/vendor
printf "\n\n%s\n\n" "-----------------------------------------------"

#
# Hadoop
#  copy hadoop/conf and hadoop/lib into /opt/sas/viya
#
if [[ -d hadoop/lib && -d hadoop/conf ]]
then
    mkdir -p /opt/sas/viya/config/data/hadoop
    chown sas:sas /opt/sas/viya/config/data/hadoop
    chmod 755 /opt/sas/viya/config/data/hadoop
    mv hadoop/conf /opt/sas/viya/config/data/hadoop
    mv hadoop/lib /opt/sas/viya/config/data/hadoop
fi


#
#
#
if [[ -d oracle ]]
then
    yum -y install libaio
    yum -y install oracle/oracle*

    version=$(yum list installed | grep oracle- | grep -v sas | head -1)
    echo Oracle $version installed

    number=$(echo $version | sed -E 's/[^0-9\.]+([0-9]+\.[0-9]+).*/\1/')
    ORACLE_HOME=/usr/lib/oracle/$number/client64
    cat <<EOF >>/opt/sas/viya/config/etc/workspaceserver/default/workspaceserver_usermods.sh
export ORACLE_HOME=$ORACLE_HOME
export TWO_TASK=ORACLE_SID
export PATH=$PATH:$ORACLE_HOME/bin
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:\$LD_LIBRARY_PATH
EOF

    cat <<EOF >>/opt/sas/viya/config/etc/cas/default/cas_usermods.settings
export ORACLE_HOME=$ORACLE_HOME
export PATH=$ORACLE_HOME/bin:$PATH
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:\$LD_LIBRARY_PATH
EOF

    cat <<EOF >>/etc/profile.d/oracle.sh
export ORACLE_HOME=$ORACLE_HOME
export PATH=$ORACLE_HOME/bin:$PATH
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:\$LD_LIBRARY_PATH
EOF

    # SAS has an unhealthy desire for version11.1 of this library.  make a symlink if you need to
    if [[ ! -f $ORACLE_HOME/lib/libclntsh.so.11.1 ]]
    then
        ln -s $ORACLE_HOME/lib/libclntsh.so.* $ORACLE_HOME/lib/libclntsh.so.11.1
    fi

    if [[ -f oracle/tnsnames.ora ]] 
    then
        cp oracle/tnsnames.ora /etc
        echo "export TNS_ADMIN=/etc" >> /opt/sas/viya/config/etc/workspaceserver/default/workspaceserver_usermods.sh
        echo "export TNS_ADMIN=/etc" >> /opt/sas/viya/config/etc/cas/default/cas_usermods.settings
        echo "export TNS_ADMIN=/etc" >> /etc/profile.d/oracle.sh
    fi
fi


exit


# clean up
cd /opt/sas
rm -rf /opt/sas/vendor
yum clean all 
rm -rf /var/cache/yum


