httpproxy:
  roles:
  - tini
  - sas-prerequisites
  - httpproxy
  - cloud-config
  ports:
  - "80:8080"
  - "443:6443"
  #environment:
  #- "SAS_VERSION=3.5"
  # TODO
  #volumes:
  #- static-content:/httpproxy
  resources:
    limits:
    - "memory=1024Mi"
    requests:
    - "memory=250Mi"

programming:
  user: root
  roles:
  - tini
  - sas-prerequisites
  - sas-java
  - programming
  - spawner-config
  - batchserver
  - connect-config
  - sas-studio-config
  - cloud-config
  ports:
  - "7080:7080"
  resources:
    limits:
    - "memory=12000Mi"
    requests:
    - "memory=512Mi"
  secrets:
  - "SETINIT_TEXT_ENC="

sas-casserver-primary:
  user: root
  roles:
  - tini
  - sas-prerequisites
  - sas-java
  - sas-casserver-primary
  - cloud-config
  ports:
  - "5570:5570"
  - "5571:5571"
  - "8777:8777"
  environment:
  - "CASENV_ADMIN_USER=sasdemo"
  - "CASENV_CAS_VIRTUAL_PROTO=http"
  - "CASENV_CAS_VIRTUAL_HOST={{ PROJECT_NAME }}.{{ SAS_K8S_NAMESPACE }}.{{ SAS_K8S_INGRESS_DOMAIN }}"
  - "CASENV_CASDATADIR=/cas/data"
  - "CASENV_CASPERMSTORE=/cas/permstore"
  - "CASCFG_MODE=smp"
  resources:
    limits:
    - "memory=12000Mi"
    requests:
    - "memory=1024Mi"
  secrets:
  - "SETINIT_TEXT_ENC="
  - "CASKEY=REPLACE ME with unique text. This is used to allow CAS workers to talk to the CAS controller"
  volumes:
  - "data=/cas/data"
  - "cache=/cas/cache"
  - "permstore=/cas/permstore"
