#!/bin/bash

#
# Copyright 2018 SAS Institute Inc.
#
# This work is licensed under a Creative Commons Attribution 4.0 International License.
# You may obtain a copy of the License at https://creativecommons.org/licenses/by/4.0/ 
#


set -x

docker run -d --rm \
  --name viyasas \
  -v $PWD:/shared \
  -w /shared \
  sasawb:build \
 /usr/local/bin/sas -nodms "$@"
