#!/bin/bash

# Exit out if any process returns a non zero return code
set -e

# Enable debugging if SAS_DEBUG is set
[[ -z ${SAS_DEBUG+x} ]] && export SAS_DEBUG=0
if [ ${SAS_DEBUG} -gt 0 ]; then
    set -x
fi

# if given a command, run that
if [[ -n "$1" ]]; then
  exec "$@"
fi

###############################################################################
# Configure httpd
###############################################################################

[[ -z $APACHE_ROOT ]] && APACHE_ROOT=
[[ -z $APACHE_CTL ]] && APACHE_CTL=$APACHE_ROOT/usr/sbin/apachectl

if [ -z $APACHE_CONF_D ]; then
  if [ -d $APACHE_ROOT/etc/httpd/conf.d ]; then
    APACHE_CONF_D=$APACHE_ROOT/etc/httpd/conf.d
    APACHE_CONF=$APACHE_ROOT/etc/httpd/conf/httpd.conf
    APACHE_BIN=/usr/sbin/httpd
    APACHE_DOCROOT=/var/www/html
    APACHE_PID=/var/run/httpd/httpd.pid
  else
    APACHE_CONF_D=$APACHE_ROOT/etc/apache2/conf.d
    APACHE_CONF=$APACHE_ROOT/etc/apache2/httpd.conf
    APACHE_BIN=/usr/sbin/apachectl
    APACHE_DOCROOT=/srv/www/htdocs
    APACHE_PID=/var/run/httpd.pid
  fi
fi

if [[ $SAS_VERSION == "3.5" ]]; then
  # This is the Viya 3.5/19w47 version of the proxy config.
  cat > $APACHE_CONF_D/proxy.conf << HTTPD
ServerName localhost
RedirectMatch "^/$" /SASStudio

# Proxy configuration for SAS services
ProxyPreserveHost On

<location /cas-shared-default-http>
  ProxyPass         http://{{ PROJECT_NAME }}-cas:8777/cas-shared-default-http
  ProxyPassReverse  http://{{ PROJECT_NAME }}-cas:8777/cas-shared-default-http
  RequestHeader set Origin "http://{{ PROJECT_NAME }}-cas:8777"
</Location>

RedirectMatch "^/SASStudio/mobile.*$" /SASStudio/not_supported

Redirect         /SASStudio  /SASStudio/
ProxyPass        /SASStudio/ http://{{ PROJECT_NAME }}-programming:7080/SASStudio/
ProxyPassReverse /SASStudio/ http://{{ PROJECT_NAME }}-programming:7080/SASStudio/
HTTPD

else
    # This is the pre Viya 3.5/19w47 version of the proxy config.
    cat > $APACHE_CONF_D/proxy.conf << HTTPD
RedirectMatch "^/$" /SASStudio

<location /cas-shared-default-http>
  ProxyPass         http://localhost:8777/cas-shared-default-http
  ProxyPassReverse  http://localhost:8777/cas-shared-default-http
  RequestHeader set Origin "http://localhost:8777"
</Location>

<Location /SASStudio/mobile>
  RedirectMatch "^/SASStudio/mobile.*$" /SASStudio/not_supported
</Location>

<Location /SASStudio>
  ProxyPass        http://localhost:7080/SASStudio
  ProxyPassReverse http://localhost:7080/SASStudio
  RequestHeader set Origin "http://localhost:7080"
</Location>
HTTPD

fi
#
# Write out a help page to be displayed when browsing port 80
#

cat > $APACHE_DOCROOT/index.html <<'EOF'
<html>
 <h1> SAS Viya Programming Docker Container </h1>
 <p> Access the software by browsing to:
 <ul>
  <li> <b><a href="/SASStudio">/SASStudio</a></b>
 </ul> using HTTP on port 8080.
 <p> If port 80 is forwarded to a different port on the host machine, use the host port instead.
 <p> Use the <b>sasdemo</b> / <b>sasdemo</b> login to access SAS Studio and CAS.
</html>
EOF

###############################################################################
# Logging
###############################################################################
sed -ri -e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' $APACHE_CONF
sed -ri -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' $APACHE_CONF

###############################################################################
# Change user
###############################################################################
sed -ri -e 's!^User apache!User sas!g' $APACHE_CONF
sed -ri -e 's!^Group apache!Group sas!g' $APACHE_CONF

###############################################################################
# Change user
###############################################################################
sed -ri -e 's!^Listen 80!Listen 8080!g' $APACHE_CONF
sed -ri -e 's!^Listen 443!Listen 6443!g' $APACHE_CONF_D/ssl.conf

###############################################################################

###############################################################################
# Run httpd
###############################################################################

$APACHE_BIN -DFOREGROUND
