---
# tasks file for pgpoolc
#
- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Install java
  include_role:
    name: sas-java

- name: Ensures directories exist before copying files to those locations
  file: path={{ SASHOME }}/share/pgpool-II state=directory

- name: Copy files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "{{ SASHOME }}/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: sas-pgpool, path: "bin", mode: "0755" }
  - { name: failover.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }
  - { name: pcppass.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pcp.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pgpool.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pool_hba.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pgpool_stop.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }
  - { name: sds_consul_health_check.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }
  - { name: node_watcher.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }

- name: Copy files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: sas-viya-pgpool-default, path: "etc/init.d/", mode: "0755" }

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Set permissions on the /var/run/sas directory
  file:
    path: /var/run/sas
    state: directory
    mode: 0775

- name: Make sure the data directory exists
  file:
    path: "{{ SAS_CONFIG_ROOT }}/data/sasdatasvrc/postgres"
    state: directory
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: 0750

- name: Make sure the oid directory exists
  file:
    path: "/oiddir"
    state: directory
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: 0750
