#!/bin/bash

# Exit out if any process returns a non zero return code
set -e

# Enable debugging if SAS_DEBUG is set
[[ -z ${SAS_DEBUG+x} ]] && export SAS_DEBUG=0
if [ ${SAS_DEBUG} -gt 0 ]; then
    set -x
fi

 # if given a command, run that
 if [[ -n "$1" ]]; then
     exec "$@"
 fi

 ###############################################################################
# Variables
###############################################################################

[[ -z ${DEPLOYMENT_NAME+x} ]]   && export DEPLOYMENT_NAME="viya"
[[ -z ${SASSERVICENAME+x} ]]    && export SASSERVICENAME="sas-rabbitmq-server"
[[ -z ${SASSERVICECONTEXT+x} ]] && export SASSERVICECONTEXT=${SASSERVICENAME#sas-}
[[ -z ${SASROOT+x} ]]           && export SASROOT=/opt/sas
[[ -z ${SASDEPLOYID+x} ]]       && export SASDEPLOYID=viya
[[ -z ${SASINSTANCE+x} ]]       && export SASINSTANCE=default
[[ -z ${SASHOME+x} ]]           && export SASHOME=${SASROOT}/${SASDEPLOYID}/home
[[ -z ${SASCONFIG+x} ]]         && export SASCONFIG=${SASROOT}/${SASDEPLOYID}/config
[[ -z ${SASTOKENDIR+x} ]]       && export SASTOKENDIR=${SASCONFIG}/etc/SASSecurityCertificateFramework/tokens/consul/default
[[ -z ${SAS_CURRENT_HOST+x} ]]  && export SAS_CURRENT_HOST=$(hostname -f)

export APP_NAME="{{ role_name }}"

# The following are used in sas-start-functions
servicename=${SASSERVICENAME}
servicecontext=${SASSERVICECONTEXT}

# Set of functions for supporting docker containers
source ${SASHOME}/lib/envesntl/docker-functions

###############################################################################
# Setup Consul
###############################################################################

# Write tokens to disk if needed and echo CONSUL_HTTP_ADDR to file
docker_define_consul_environment

# start local consul
#/etc/init.d/sas-viya-consul-default start
docker_run_local_consul

# Wait for Consul to be up
#docker_wait_for_consul_leader


###############################################################################
# Shutdown
###############################################################################
function gracefulshutdown {
    echo
    echo_line "Shutting down ${SASSERVICECONTEXT} pid $(cat ${DOCKERPIDFILE})!"
    echo

    ${SASHOME}/bin/sas-rabbitmq-registration -x

    # new SAS init stuff
    kill -TERM $(cat ${DOCKERPIDFILE})
    result=$?
    # sleep 10
    echo
    if [ $result -eq 0 ]; then
        echo_line "SUCCESS: ${SASSERVICECONTEXT} is stopped"
    else
        echo_line "ERROR: ${SASSERVICECONTEXT} could not be stopped"
    fi

    exit 0
}

trap gracefulshutdown SIGTERM
trap gracefulshutdown SIGINT

###############################################################################
# Run rabbitmq
###############################################################################

# Fix the ownership of the directory.
chown -v sasrabbitmq:sas /opt/sas/viya/config/var/lib/rabbitmq-server/sasrabbitmq

RABBITMQ_USE_LONGNAME=no
export RABBITMQ_USE_LONGNAME
[[ -z ${RABBITMQ_DATA_DIR+x} ]] && export RABBITMQ_DATA_DIR=/rabbitmq/data

docker_create_pid_file

chmod -v 0777 ${DOCKERPIDFILE}

if [ ! -d ${RABBITMQ_DATA_DIR} ]; then
  echo ""
  mkdir -vp ${RABBITMQ_DATA_DIR}
  chown -v sasrabbitmq:sas ${RABBITMQ_DATA_DIR}
  chmod -v 0755 ${RABBITMQ_DATA_DIR}
  echo ""
fi
chown -vR sasrabbitmq:sas "$(dirname "${RABBITMQ_DATA_DIR}")"

if [[ -e ${SASCONFIG}/etc/SASSecurityCertificateFramework/tokens/rabbitmq/default/erlang.cookie ]];then
  cp ${SASCONFIG}/etc/SASSecurityCertificateFramework/tokens/rabbitmq/default/erlang.cookie ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
  chown sasrabbitmq:sas ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
  chmod 600 ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
fi

if [[ "${SECURE_CONSUL}" == "true" ]]; then
  copy_token_from_configmap "${VAULT_TOKEN_DIR}" "${APP_NAME}" "${APP_NAME}"
fi

echo_line "Starting ${SASSERVICENAME}..."

${SASHOME}/bin/${SASSERVICENAME} -r ${SASROOT}/${SASDEPLOYID} -m ${RABBITMQ_DATA_DIR} -p ${DOCKERPIDFILE}

# I am seeing consistent issues when we start everything at once.
# We will do one more check to see if Consul has a leader and then we will
# try the kv write.
#docker_wait_for_consul_leader

# if in k8s, set up HA
if [ $(env|grep KUBERNETES_|wc -l) -gt 0 ]; then
  hostname_index=$(hostname|sed -E 's/^.*-([0-9]+)$/\1/g')
  if [[ $hostname_index -eq 0 ]]; then
    ${SASHOME}/sbin/rabbitmqctl -q set_policy ha-all "^sas\." '{"ha-mode":"all", "ha-sync-mode": "automatic"}'
  else
    hostname_base=$(hostname|sed -E 's/^(.*)-[0-9]+$/\1/g')
    hostname_domain=$(hostname -d)
    ${SASHOME}/sbin/rabbitmqctl stop_app
    ${SASHOME}/sbin/rabbitmqctl join_cluster rabbit@${hostname_base}-0.${hostname_domain}
    ${SASHOME}/sbin/rabbitmqctl start_app
  fi
fi

${SASHOME}/bin/sas-rabbitmq-registration

###############################################################################
# Keep the container alive until it is killed
###############################################################################

docker_check_process


